### ISSUE TITLE
Getting error when trying to feed empty array to the table

### ISSUE THREAD

**Issue by vayter2** [arnedesmedt/vue-ads-table-tree#12]
Hello,
 could we have ability for hanling the empty table data array with some message like "no data" ?

![image](https://user-images.githubusercontent.com/40659792/51252382-f73b6180-199b-11e9-97b0-fd11a0dbc991.png)

**Comment by arnedesmedt** [comment]
I think you can do this via https://github.com/arnedesmedt/vue-ads-table-tree#2-no-rows-slot
I have add this in the latest version. Can you check if that will fix your problem.
