### ISSUE TITLE
Replace standart expanding icon with own custom icon

### ISSUE THREAD

**Issue by vayter2** [arnedesmedt/vue-ads-table-tree#13]
Hello, 

Could I ask you to implement ability to change standart "plus/minus" expanding icon with some another custom icon?

![image](https://user-images.githubusercontent.com/40659792/51603816-29ecd900-1f0b-11e9-8e8c-20b7458f58f3.png)

**Comment by renaudham** [comment]
+1 on this

**Comment by arnedesmedt** [comment]
This is now possible. See https://github.com/arnedesmedt/vue-ads-table-tree#3-sort-icon-slot
