### ISSUE TITLE
JSFiddle shows no row content

### ISSUE THREAD

**Issue by klassm** [arnedesmedt/vue-ads-table-tree#14]
Hi,

I am currently trying to upgrade to the latest version of vue-ads-table-tree. Now I am stuck at a very basic step - my table does not show any content. Thus, I had a look at the JSFiddle (https://jsfiddle.net/arnedesmedt/7my8L42q) - which has essentially the same problem - it does not show any row content.

Can you help me with this issue?

Thanks,
Matthias

**Comment by arnedesmedt** [comment]
Sorry @klassm, It was a bit of a crapy release, But I know refactored the table in 3 components so the problem is now gone.
