### ISSUE TITLE
How do I unfilter the icon for a column

### ISSUE THREAD

**Issue by zhanjunhao** [arnedesmedt/vue-ads-table-tree#16]
I tried to set the filterable of the column to false but still show the icon， How do I cancel？

**Comment by arnedesmedt** [comment]
Do you want to remove the filterable input field if all columns have a filterable property set to false?

**Comment by zhanjunhao** [comment]
I've tried to delete them all but I still have the ICONS that are displayed and I just want to turn off the filter so can I only use CSS to limit it

**Comment by arnedesmedt** [comment]
You mean the sort icons, because their are no filter icons, only a filter input field?

**Comment by zhanjunhao** [comment]
It's not that I want to get rid of the sort icon in the header of the table which property I'm going to set

**Comment by arnedesmedt** [comment]
remove the order and direction property of the column object.

**Comment by zhanjunhao** [comment]
Thank you. I hope you can update the document

**Comment by arnedesmedt** [comment]
Will add it to my, otherwise feel free to create a merge request.

**Comment by zhanjunhao** [comment]
ok thank you
