### ISSUE TITLE
No records are rendered with `bottom` slot

### ISSUE THREAD

**Issue by valdisiljuconoks** [arnedesmedt/vue-ads-table-tree#20]
hi,

when specifying template for `bottom` slot, no records are rendered.
I'm trying to "remove" paging and summary, and specify just "empty" template.

can repro on your [jsfiddle](https://jsfiddle.net/n2z8rta7/) as well. just add template:

```
<template slot="bottom">&nbsp;</template>
```

![image](https://user-images.githubusercontent.com/1767179/57987288-0afcee80-7a88-11e9-9811-fdf8e7b1d125.png)

what is proper way to remove paging at all?

**Comment by valdisiljuconoks** [comment]
what about this one? thx

**Comment by arnedesmedt** [comment]
update to 2.3.3 and a fix will be provided
