### ISSUE TITLE
How to apply style to rows with children?

### ISSUE THREAD

**Issue by valdisiljuconoks** [arnedesmedt/vue-ads-table-tree#21]
Hi,

I would like to style only those rows which have children. What would be the class selector for this?

thx

**Comment by arnedesmedt** [comment]
There is no particular selector for rows with children, but you can add the _classes property to all rows with children: See https://github.com/arnedesmedt/vue-ads-table-tree#rows

**Comment by valdisiljuconoks** [comment]
great, this works as well!
