### ISSUE TITLE
Is it possible to have pattern for column templates

### ISSUE THREAD

**Issue by valdisiljuconoks** [arnedesmedt/vue-ads-table-tree#23]
Hi,

What I'm trying to accomplish is to have the same template for many columns that following the same naming conventions. Inside the template I can survive with "props.row[props.column.property]" values, that's fine.

But in order to achieve this - seems like I need to specify template for all possible columns that might come in from the server.

Sample is here: https://codepen.io/valdisiljuconoks/pen/KLvmxe

**Comment by arnedesmedt** [comment]
You can simply list all your columns you want to format in an array (in my example 'slottedColumns') and loop over them. See: 

https://jsfiddle.net/arnedesmedt/jnpmgvr5/

**Comment by valdisiljuconoks** [comment]
great success! think I can get through with this. column list is dynamic and coming from server, but guess I can enumerate them and give it back to the client-side.

thx!

**Comment by valdisiljuconoks** [comment]
nice! it works. great. now rest of the issues needs to be resolved :) I could jump and contribute, but need to get my head around the implementation tho..
