### ISSUE TITLE
Total viewable rows after child row expansion

### ISSUE THREAD

**Issue by twoxfh** [arnedesmedt/vue-ads-table-tree#29]
I maybe missing something but I do not see how to get the total number of rows viewed by the user after clicking child row expansion button. 

I would like to set the total number of rows including child rows and each time a child row is expanded have the overage updated into the pagination. If you look at any of the examples you will see once you expand the child rows the total rows slot does not update.

Any help is appreciated.

**Comment by arnedesmedt** [comment]
The pagination component has a default number of items on each page.

If child rows are also counted as an 'item' on a page and if you expand the a parent row, the last rows of the current page will disappear. And you can't set a custom 'items per page' for only one page with the paginator.

So I think that your feature is impossible to implement.

**Comment by twoxfh** [comment]
Thanks for the sanity check and the cycles for thinking about it. Great component, thanks for sharing.
