### ISSUE TITLE
Change background color for cell

### ISSUE THREAD

**Issue by phinguyen91** [arnedesmedt/vue-ads-table-tree#40]
![image](https://user-images.githubusercontent.com/4995405/68870724-e7142000-072d-11ea-9f8b-383f588c6854.png)

How can I apply a similar style as cell Conditional?
Ex:
if value='Yes
         style="background: red"
else
         style="background: green"

Thanks

**Comment by arnedesmedt** [comment]
Thx for asking that question, I forgot to documentate it in the readme.

I've added it. See the last example and the explanation in the styling section: https://github.com/arnedesmedt/vue-ads-table-tree#examples

In this specific case and if the printscreen is the whole table it will be something like this:

```vue
<template>
    <vue-ads-table-tree :classes="classes" ...>...</vue-ads-table-tree>
</template>

<script>
export default {
    let classes = {
        'all/3': (row, column) => {
            return {'bg-red': row.[columnName] === 'Yes'};
        }
    };
}
</script>
```

**Comment by phinguyen91** [comment]
it's working. Thanks for your support
Note:
Add check undefined
`let classes = {
            'all/3': (row, column) => {
               if (row !== undefined) {
                  return { 'bg-red': row.[columnName] === 'Yes' };
               }
            }
         };`
