### ISSUE TITLE
Hide filter textbox on table

### ISSUE THREAD

**Issue by nguyen-huu-phi** [arnedesmedt/vue-ads-table-tree#41]
![image](https://user-images.githubusercontent.com/4995405/68930603-5129d500-07c1-11ea-9b2d-03bf93733513.png)
![image](https://user-images.githubusercontent.com/4995405/68930617-59821000-07c1-11ea-98dc-eb5a08e73c4b.png)
 hi @arnedesmedt . I want hide filter textbox on table. Howerver, i don't see it in GitHub docs. Pls help me
Thanks

**Comment by arnedesmedt** [comment]
Just use an empty top slot, see: https://github.com/arnedesmedt/vue-ads-table-tree#1-top

**Comment by nguyen-huu-phi** [comment]
> Just use an empty top slot, see: https://github.com/arnedesmedt/vue-ads-table-tree#1-top
Thanks, it's working
`<template slot="top">`
`                  <span></span>`
 `              </template>`
`               <template slot="bottom">`
  `                <span></span>`
 `              </template>`
