### ISSUE TITLE
Grouping bugs.

### ISSUE THREAD

**Issue by pavelav** [arnedesmedt/vue-ads-table-tree#42]
Hello @arnedesmedt ,
Seeing some issues, when grouping on multiple columns. The steps are illustrated as screenshots:
1. Initial state:
![1-initial](https://user-images.githubusercontent.com/1294691/69534080-26dad300-0f8a-11ea-90ec-958811fd7417.png)
2.1. Group by location - so far so good:
![2-group-location](https://user-images.githubusercontent.com/1294691/69534113-39550c80-0f8a-11ea-81a0-f08908c65431.png)
2.2. Then group by resource - notice how resourceA appears under domain-1 group (incorrect):
![2-group-location-resource](https://user-images.githubusercontent.com/1294691/69534163-4b36af80-0f8a-11ea-99b0-fb8882485172.png)
2.3. Things change if I try to sort. Sorting by location causes domain-1 group to vanish (incorrect):
![2-group-location-resource-sort-location](https://user-images.githubusercontent.com/1294691/69534330-9d77d080-0f8a-11ea-93fd-85031ad6eee3.png)
2.4. However if I sort by Resource instead, the table starts to look okay:
![2-group-location-resource-sort-resource](https://user-images.githubusercontent.com/1294691/69534394-c4ce9d80-0f8a-11ea-8a3f-61554f5a40f2.png)
3.1. For the sake of completeness also including screenshots when grouping by Resource first:
![3-group-resource](https://user-images.githubusercontent.com/1294691/69534438-dadc5e00-0f8a-11ea-9287-bb316e60e844.png)
3.2. And then by location (incorrect - no resourceB group):
![3-group-resource-location](https://user-images.githubusercontent.com/1294691/69534456-e760b680-0f8a-11ea-9a08-b7bc1efe4e4f.png)

You can find the Vue component I used to reproduce the issue in commit https://github.com/pavelav/vue-ads-table-tree/commit/75aaed847a751841bf97a4e0445255acc6b84785

Please take a look. Thank you!

**Comment by arnedesmedt** [comment]
Thx for the report, solved this issue in 2.4.2

**Comment by pavelav** [comment]
Great, thank you for a quick fix!
