### ISSUE TITLE
Scroll not found

### ISSUE THREAD

**Issue by sreekesh93** [arnedesmedt/vue-ads-table-tree#49]
when table data exceed the page size , scrolling is not enabled.

**Comment by arnedesmedt** [comment]
I think this is a css problem of your project. This table doesn't have any scroll logic. The same way a simple HTML table doesn't have scroll logic. Can you give me an example of your project?

**Comment by sreekesh93** [comment]
I fixed it by adding style="overflow:auto" to root tag v-container of my custom template. Thanks for the response.
