### ISSUE TITLE
¿Support for Colspan and Rowspan?

### ISSUE THREAD

**Issue by jmarcoslc** [arnedesmedt/vue-ads-table-tree#50]
Hello,

I want to use this component to display some information in my project. But I need to know first if there is a way to set colspan and rowspan on the table.

Gretings!

**Comment by arnedesmedt** [comment]
Hi,

Colspan and rowspan are not supported. This would be very difficult to implement it by the json object that is given to fill the database. See the example (rows and columns): https://github.com/arnedesmedt/vue-ads-table-tree#example
