### ISSUE TITLE
how to change placeholder filter?

### ISSUE THREAD

**Issue by silvablack** [arnedesmedt/vue-ads-table-tree#52]
In order to modify this, I need to style this filter component.

![image](https://user-images.githubusercontent.com/29361261/82834125-8e6ccf00-9e96-11ea-8766-42b45e1e8918.png)

"vue": "^2.6.10"
"vuetify": "^2.1.0"

**Comment by arnedesmedt** [comment]
You need to change the top slot: https://github.com/arnedesmedt/vue-ads-table-tree#1-top

**Comment by silvablack** [comment]
I tryied

`<template slot="top">
        <v-input slot="filter" slot-scope="props" :id="props.id" type="text" placeholder="Filtro" /></template>`

but not worked.

You can me help?

**Comment by silvablack** [comment]
> You need to change the top slot: https://github.com/arnedesmedt/vue-ads-table-tree#1-top

I tryied

`<template` slot="top">
 <v-input slot="filter" slot-scope="props" :id="props.id" type="text" placeholder="Filtro" /></template>`

but not worked.

You can me help?

**Comment by silvablack** [comment]
@arnedesmedt thnks man. but
I tryied
`<template slot="top"> <v-input slot="filter" slot-scope="props" :id="props.id" type="text" placeholder="Filtro" /></template>`
but not worked.
You can me help?
thanks advanced
