### ISSUE TITLE
How to add class to thead

### ISSUE THREAD

**Issue by ghost** [arnedesmedt/vue-ads-table-tree#58]
I want to custom class names to thead, but I didn't find any ways.
Styling is for table, tr, th, and td. but I want thead or tbody.
How can I solve this?

**Comment by arnedesmedt** [comment]
There is a styling section in the README that will explain this: https://github.com/arnedesmedt/vue-ads-table-tree#styling use the 0-index for the header.

**Comment by ghost** [comment]
I know 0-index is for the header, but it doesn't indicate thead tag exactly.
I want styling for thead tag.

**Comment by arnedesmedt** [comment]
The styling is on the tr tag in the thead. 

Why not using a custom css file to style the thead?
