### ISSUE TITLE
Custom table header

### ISSUE THREAD

**Issue by jrebmann** [arnedesmedt/vue-ads-table-tree#65]
Hello,

I am trying to add a progress indicator in the header of my table. Is it possible to access a header slot?

I have now searched longer in the documentation, but only found the possibility to style the header. But this is not enough for me, because I want to extend the header with HTML elements.

I would be very grateful for help.

**Comment by arnedesmedt** [comment]
If you look into https://github.com/arnedesmedt/vue-ads-table-tree/blob/develop/src/components/TableContainer.vue you can see that you can override the top slot to use custom html elements
