### ISSUE TITLE
Expand/collapse children by clicking on whole row

### ISSUE THREAD

**Issue by uykusuz** [arnedesmedt/vue-ads-table-tree#68]
Hi,

Is it possible to toggle expansion of the children by clicking on the whole row instead of only the span containing the actual text?

**Comment by arnedesmedt** [comment]
Yes, that should be possible, but this should be configurable. You can create a PR for this, I'll review it. Thx in advance!

**Comment by uykusuz** [comment]
Alright, I'll tackle it as soon as it goes on our nerves to much :D Do you know how difficult it would be to upgrade your table to vue 3?

**Comment by arnedesmedt** [comment]
I'm currently not have any vue 3 projects so I don't need it in Vue3. If you want to change it to Vue 3: feel free to make a PR. Thx in advance!

**Comment by uykusuz** [comment]
Alright, we'll do as soon as it hurts too much :) Thank you for your fast responses!
