### ISSUE TITLE
Use Images for toggle-children-icon

### ISSUE THREAD

**Issue by uykusuz** [arnedesmedt/vue-ads-table-tree#69]
Hi,

I want to use images for the `toggle-children-icon`. Can you tell me how I could do that? I have to switch on the `props.expanded`, so I don't know how to express that. Perhaps I'm just not proficient enough with Vue yet :D

**Comment by arnedesmedt** [comment]
As shown in the example: https://github.com/arnedesmedt/vue-ads-table-tree#example

You should replace the - en + sign with your image.

**Comment by uykusuz** [comment]
thanks for the fast response! :)

> As shown in the example: https://github.com/arnedesmedt/vue-ads-table-tree#example
> 
> You should replace the - en + sign with your image.

That's not possible. If I simply replace the string to be returned to a tag, the tag is rendered as text, i.e. I see something like `<img src... />` instead of the image itself. I tried then using a `v-if` directive on the `props.expanded`, but that doesn't work. I guess I can't use the `v-if` directive in that way.
Do you have a hint?

**Comment by arnedesmedt** [comment]
Are you placing the img tag inside the quotes? Because that is wrong.

**Comment by uykusuz** [comment]
Great, it works now. Thank you for your help!
