### ISSUE TITLE
Issue with the slot template to format cell content

### ISSUE THREAD

**Issue by renaudham** [arnedesmedt/vue-ads-table-tree#7]
Hi.
Great job.

The cell content formater, as I see here

<template
                    slot="firstName"
                    slot-scope="props">
                    <a
                        :href="`https://www.google.com/search?q=${props.row.firstName}+${props.row.lastName}`"
                        target="_blank">{{ props.row.firstName }}</a>
</template>

is just not working
whatever cell we try to format by this way is never changing the cell content..

How to do?

Thanks

**Comment by arnedesmedt** [comment]
Your right I'm looking for a solution.

**Comment by arnedesmedt** [comment]
update to 1.2.4 and your 2 issues will be solved.
