### ISSUE TITLE
Impossible to add some extra columns before the "name"  (firstName in demo) 

### ISSUE THREAD

**Issue by renaudham** [arnedesmedt/vue-ads-table-tree#8]
Hi

Great job.

Anyway I have an issue

if I try to add extra columns like for example an ID column, on first left position, 
and I would like to keep the nodes children opener on the second column firstName
I can't, apparenlty its always set to the first column

any way to set what column will get the nodes childern opener?

thanks

**Comment by arnedesmedt** [comment]
Now, the arrow is indeed always placed in the first column. In 1.2.4 I added an option in the column object. Read the README to see how it's implemented.
